FROM golang:1.18 as builder

RUN apt-get update && apt-get install -y protobuf-compiler

# Install Go plugins for protoc (compatible with Go 1.18)
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

ENV PATH="/go/bin:${PATH}"

WORKDIR /workspace 